export const DECISION = {
  BUY: "Buy",
  SELL: "Sell",
  HOLD: "_",
};

export const FORM_ACTIONS = {
  LOAD_SYMBOLS: "LOAD_SYMBOLS",
  LOAD_SYMBOLS_SUCCESS: "LOAD_SYMBOLS_SUCCESS",
  LOAD_SYMBOLS_FAIL: "LOAD_SYMBOLS_FAIL",
  SET_SYMBOL: "SET_SYMBOL",
  SET_TIME_WINDOW: "SET_TIME_WINDOW",
  SET_USE_SOCIAL_MEDIA: "SET_USE_SOCIAL_MEDIA",
};
