export const DECISION_ACTION = {
    BUY: 'Buy',
    SELL: 'SELL',
    HOLD: 'Hold'
}

export const FORM_ACTIONS = {
    LOAD_SYMBOLS: 'LOAD_SYMBOLS',
    LOAD_SYMBOLS_SUCCESS: 'LOAD_SYMBOLS_SUCCESS',
    SET_SYMBOL: 'SET_SYMBOL',
    SET_TIME_WINDOW: 'SET_TIME_WINDOW',
    SET_USE_SOCIAL_MEDIA: 'SET_USE_SOCIAL_MEDIA',
}